env:
  browser: true
  node: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  quote-props: ["error", "consistent"]
  dot-notation: ["error", {"allowPattern":".*"}]
  brace-style: ["error", "stroustrup"]
  no-console": ["error", { allow: ["warn"] }] 